### ISSUE TITLE
Default explanation text for `mobile-center test` is poorly formatted

### ISSUE THREAD

**Issue by dvdsgl** [Microsoft/mobile-center-cli#93]
`mobile-center test` produces this output:

![image](https://cloud.githubusercontent.com/assets/108197/21202605/e4147534-c203-11e6-86bc-24052db1e603.png)

**Comment by christav** [comment]
I've done some investigation. The help system is properly pulling the information to display out, but the `cli-table2` module that's being used for formatting isn't building the table correctly. I'm guessing there's issues when the width of the table is larger than the width of the terminal.

I was thinking of trying to set an explicit size on the table columns instead of letting it pick them automatically and see if that fixes the problem. If it doesn't we'll need to write a bunch of manual formatting stuff.

**Comment by christav** [comment]
Fixed in #101
